version: '3.8'

services:
  mysql:
    container_name: mysql
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: parcial1Lab4
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - my_network

  hotel:
    container_name: hotel
    image: danicattaneob/labo-iv-final-2023-12-19:latest
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    networks:
      - my_network

  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/parcial1Lab4
      EXTERNAL_API: http://hotel:8080
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
    ports:
      - "8081:8081"
    depends_on:
      - mysql
      - hotel
    networks:
      - my_network

volumes:
  mysql_data:

networks:
  my_network:
    driver: bridge
